# Copyright (C) 1991, 1992, 1993 Free Software Foundation, Inc.
# This file is part of the GNU C Library.

# The GNU C Library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Library General Public License as
# published by the Free Software Foundation; either version 2 of the
# License, or (at your option) any later version.

# The GNU C Library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Library General Public License for more details.

# You should have received a copy of the GNU Library General Public
# License along with the GNU C Library; see the file COPYING.LIB.  If
# not, write to the Free Software Foundation, Inc., 675 Mass Ave,
# Cambridge, MA 02139, USA.

#
#	Master Makefile for the GNU C library
#
ifneq (,)
This makefile requires GNU Make.
endif


# This is the default target; it makes everything except the tests.
.PHONY: all
all: lib others

configure: configure.in
	autoconf $(ACFLAGS)

%/configure: %/configure.in
	autoconf $(ACFLAGS) $< > $@.new
	mv $@.new $@

include Makeconfig

include $(objpfx)sysd-dirs
define \n


endef
sysdep-subdirs := $(subst $(\n), ,$(sysdep-subdirs))

# These are the subdirectories containing the library source.
+ansi_dirs	:= assert ctype locale math setjmp \
		   signal stdio stdlib malloc string time
+posix_dirs	:= dirent grp pwd posix io termios
+other_dirs	:= resource socket misc gnulib $(wildcard crypt) manual
subdirs		:= $(strip $(+ansi_dirs) $(+posix_dirs) $(+other_dirs) \
			   $(sysdep-subdirs))
export subdirs := $(subdirs)	# Benign, useless in GNU make before 3.63.

# The mach and hurd subdirectories have many generated header files which
# the much of rest of the library depends on, so it is best to build them
# first (and mach before hurd, at that).  The before-compile additions in
# sysdeps/{mach,hurd}/Makefile should make it reliably work for these files
# not to exist when making in other directories, but it will be slower that
# way with more somewhat expensive `make' invocations.
subdirs	:= $(filter mach,$(subdirs)) $(filter hurd,$(subdirs)) \
	   $(filter-out mach hurd,$(subdirs))

# All initialization source files.
+subdir_inits	:= $(wildcard $(foreach dir,$(subdirs),$(dir)/init-$(dir).c))
# All subdirectories containing initialization source files.
+init_subdirs	:= $(patsubst %/,%,$(dir $(+subdir_inits)))


# These are the targets that are made by making them in each subdirectory.
+subdir_targets	:= subdir_lib objects objs others mostlyclean		\
		   subdir_clean tests subdir_lint.out 			\
		   subdir_echo-headers subdir_echo-distinfo		\
		   subdir_install $(addprefix install-,			\
					      no-libc.a bin lib		\
					      data headers others)

headers := features.h stubs.h errno.h sys/errno.h errnos.h limits.h \
	   $(stddef.h) $(stdarg.h)

echo-headers: subdir_echo-headers

ifdef +gnu-stabs
# We're using the GNU linker, so we use the set-element init function.
+init := set-init
else
# We're not using the GNU linker, so we use the munch init function.
+init := munch-init

$(objpfx)munch-init.c: munch.awk munch-tmpl.c $(+subdir_inits)
	awk -f $< subdirs='$(+init_subdirs)' $(word 2,$^) > $@-t
	mv $@-t $@
generated := $(generated) $(objpfx)munch-init.c
endif

aux	:= sysdep $(+init) version start


# What to install.
install-lib = crt0.o Mcrt1.o	# libc.a is done by Makerules.


include Makerules

# Install from subdirectories too.
install: subdir_install

# `crt0' is the traditional name for the startup code,
# so that's what we install start.o as.
$(objpfx)crt0.o: $(objpfx)start.o
	-rm -f $@
	ln $< $@

$(objpfx)Mcrt1.o:
	cp /dev/null $(objpfx)Mcrt1.c
	$(COMPILE.c) $(objpfx)Mcrt1.c $(OUTPUT_OPTION)
	rm -f $(objpfx)Mcrt1.c

lib-noranlib: subdir_lib


$(objpfx)sysd-dirs: $(+sysdir_pfx)config.make
	(echo define sysdep-subdirs;					      \
	 for dir in $(sysdirs); do					      \
	   if [ -r $(sysdep_dir)/$$dir/Subdirs ]; then			      \
	     cat $(sysdep_dir)/$$dir/Subdirs;				      \
	   else true;							      \
	   fi;								      \
	 done;								      \
	 echo endef) > $@-tmp
	 mv $@-tmp $@

# Makerules creates a file `stub-$(subdir)' for each subdirectory, which
# contains `#define __stub_FUNCTION' for each function which is a stub.
# Here we paste all of these together into <stubs.h>.

subdir-stubs := $(foreach dir,$(subdirs),$(common-objpfx)stub-$(dir))

# Call the subdirs to make their stub-SUBDIR files.
$(subdir-stubs): $(common-objpfx)stub-%: FORCE
	$(MAKE) -C $* stubs
FORCE:

$(objpfx)stubs.h: $(common-objpfx)stub- $(subdir-stubs)
	(echo '/* This file is automatically generated.';\
	 echo '   It defines a symbol `__stub_FUNCTION'\'' for each function';\
	 echo '   in the C library which is a stub, meaning it will fail';\
	 echo '   every time called, usually setting errno to ENOSYS.  */';\
	 sort $^) > $@.new
	mv $@.new $@

# This makes the Info or DVI file of the documentation from the Texinfo source.
.PHONY: info dvi
info dvi:
	$(MAKE) -C manual $@

# This makes all the subdirectory targets.

# For each target, make it depend on DIR/target for each subdirectory DIR.
$(+subdir_targets): %: $(addsuffix /%,$(subdirs))

# Compute a list of all those targets.
all-subdirs-targets := $(foreach dir,$(subdirs),\
				 $(addprefix $(dir)/,$(+subdir_targets)))

# The action for each of those is to cd into the directory and make the
# target there.
$(all-subdirs-targets):
	$(MAKE) -C $(@D) $(@F)

.PHONY: $(+subdir_targets) $(all-subdirs-targets)

# This clobbers everything that can be regenerated.
.PHONY: clean realclean distclean
realclean: distclean
clean:
	-rm -f $(objects) $(+depfiles) munch-init.c $(objpfx)depend-
	-rm -f $(libc.a) $(addprefix $(objpfx),$(install-lib)) core TAGS
	-rm -f $(addprefix $(+sysdir_pfx),sysd-Makefile sysd-dirs sysdirs)
# This is done this way rather than having `subdir_clean' be a
# dependency of this target so that libc.a will be removed before the
# subdirectories are dealt with and so they won't try to remove object
# files from it when it's going to be removed anyway.
	@$(MAKE) subdir_clean no_deps=t

distclean: clean
	-rm -f $(addprefix $(objpfx),config.status config.make \
				     sysd-Makefile sysd-dirs)
ifdef objdir
	-rm -f $(objpfx)Makefile
endif

.PHONY: echo_subdirs
echo_subdirs:;@echo '$(subdirs)'

.PHONY: echo-distinfo parent_echo-distinfo
echo-distinfo: parent_echo-distinfo subdir_echo-distinfo
parent_echo-distinfo:
	@echo $(addprefix +header+,$(headers)) \
	      $(addprefix +nodist+,$(generated))

# Make the distribution tarfile.

distribute  := README INSTALL NOTES COPYING.LIB COPYING ChangeLog NEWS	\
	       Makefile Makeconfig Makerules Rules Make-dist MakeTAGS	\
	       ansidecl.h mkinstalldirs move-if-change			\
	       configure configure.in aclocal.m4 config.sub config.guess\
	       munch-tmpl.c munch.awk gnu-stabs.h sysdep.h

export distribute := $(strip $(distribute))
export generated := $(generated) $(objpfx)stubs.h

.PHONY: dist
dist: Make-dist $(distribute)
	$(MAKE) -f $< no_deps=t $(Make-dist-args)

README: README.template version.c ; # Make-dist should update README.

INSTALL: manual/maint.texi
	makeinfo --no-validate --no-warn --no-headers $< -o $@
