#ifndef	_ENDIAN_H

#define	_ENDIAN_H	1	

/* This file should define either __BIG_ENDIAN or __LITTLE_ENDIAN,
   as appropriate for the machine in question.

   If only the stub endian.h applies to a particular configuration,
   endian.h is generated by running a program on the host machine.
   So if cross-compiling to a machine with a different byte order,
   the endian.h file for that machine must exist.  */

#error Machine byte order unknown.

#endif /* endian.h */
