/* This file generated by errnos.awk from
     errno.texi
     mach/message.h
     mach/kern_return.h
     mach/mig_errors.h
     device/device_types.h
   Do not edit this file; edit errnos.awk and regenerate it.  */

#ifndef _BITS_ERRNO_H
#define _BITS_ERRNO_H 1

#if !defined _ERRNO_H
# error "Never include <bits/errno.h> directly; use <errno.h> instead."
#endif

/* The Hurd uses Mach error system 0x10, subsystem 0. */

#define EPERM                          0x40000001	/* Operation not permitted */
#define ENOENT                         0x40000002	/* No such file or directory */
#define ESRCH                          0x40000003	/* No such process */
#define EINTR                          0x40000004	/* Interrupted system call */
#define EIO                            0x40000005	/* Input/output error */
#define ENXIO                          0x40000006	/* No such device or address */
#define E2BIG                          0x40000007	/* Argument list too long */
#define ENOEXEC                        0x40000008	/* Exec format error */
#define EBADF                          0x40000009	/* Bad file descriptor */
#define ECHILD                         0x4000000a	/* No child processes */
#define EDEADLK                        0x4000000b	/* Resource deadlock avoided */
#define ENOMEM                         0x4000000c	/* Cannot allocate memory */
#define EACCES                         0x4000000d	/* Permission denied */
#define EFAULT                         0x4000000e	/* Bad address */
#define ENOTBLK                        0x4000000f	/* Block device required */
#define EBUSY                          0x40000010	/* Device or resource busy */
#define EEXIST                         0x40000011	/* File exists */
#define EXDEV                          0x40000012	/* Invalid cross-device link */
#define ENODEV                         0x40000013	/* No such device */
#define ENOTDIR                        0x40000014	/* Not a directory */
#define EISDIR                         0x40000015	/* Is a directory */
#define EINVAL                         0x40000016	/* Invalid argument */
#define EMFILE                         0x40000018	/* Too many open files */
#define ENFILE                         0x40000017	/* Too many open files in system */
#define ENOTTY                         0x40000019	/* Inappropriate ioctl for device */
#define ETXTBSY                        0x4000001a	/* Text file busy */
#define EFBIG                          0x4000001b	/* File too large */
#define ENOSPC                         0x4000001c	/* No space left on device */
#define ESPIPE                         0x4000001d	/* Illegal seek */
#define EROFS                          0x4000001e	/* Read-only file system */
#define EMLINK                         0x4000001f	/* Too many links */
#define EPIPE                          0x40000020	/* Broken pipe */
#define EDOM                           0x40000021	/* Numerical argument out of domain */
#define ERANGE                         0x40000022	/* Numerical result out of range */
#define EAGAIN                         0x40000023	/* Resource temporarily unavailable */
#define EWOULDBLOCK                    EAGAIN
#define EINPROGRESS                    0x40000024	/* Operation now in progress */
#define EALREADY                       0x40000025	/* Operation already in progress */
#define ENOTSOCK                       0x40000026	/* Socket operation on non-socket */
#define EMSGSIZE                       0x40000028	/* Message too long */
#define EPROTOTYPE                     0x40000029	/* Protocol wrong type for socket */
#define ENOPROTOOPT                    0x4000002a	/* Protocol not available */
#define EPROTONOSUPPORT                0x4000002b	/* Protocol not supported */
#define ESOCKTNOSUPPORT                0x4000002c	/* Socket type not supported */
#define EOPNOTSUPP                     0x4000002d	/* Operation not supported */
#define EPFNOSUPPORT                   0x4000002e	/* Protocol family not supported */
#define EAFNOSUPPORT                   0x4000002f	/* Address family not supported by protocol */
#define EADDRINUSE                     0x40000030	/* Address already in use */
#define EADDRNOTAVAIL                  0x40000031	/* Cannot assign requested address */
#define ENETDOWN                       0x40000032	/* Network is down */
#define ENETUNREACH                    0x40000033	/* Network is unreachable */
#define ENETRESET                      0x40000034	/* Network dropped connection on reset */
#define ECONNABORTED                   0x40000035	/* Software caused connection abort */
#define ECONNRESET                     0x40000036	/* Connection reset by peer */
#define ENOBUFS                        0x40000037	/* No buffer space available */
#define EISCONN                        0x40000038	/* Transport endpoint is already connected */
#define ENOTCONN                       0x40000039	/* Transport endpoint is not connected */
#define EDESTADDRREQ                   0x40000027	/* Destination address required */
#define ESHUTDOWN                      0x4000003a	/* Cannot send after transport endpoint shutdown */
#define ETOOMANYREFS                   0x4000003b	/* Too many references: cannot splice */
#define ETIMEDOUT                      0x4000003c	/* Connection timed out */
#define ECONNREFUSED                   0x4000003d	/* Connection refused */
#define ELOOP                          0x4000003e	/* Too many levels of symbolic links */
#define ENAMETOOLONG                   0x4000003f	/* File name too long */
#define EHOSTDOWN                      0x40000040	/* Host is down */
#define EHOSTUNREACH                   0x40000041	/* No route to host */
#define ENOTEMPTY                      0x40000042	/* Directory not empty */
#define EPROCLIM                       0x40000043	/* Too many processes */
#define EUSERS                         0x40000044	/* Too many users */
#define EDQUOT                         0x40000045	/* Disk quota exceeded */
#define ESTALE                         0x40000046	/* Stale file handle */
#define EREMOTE                        0x40000047	/* Object is remote */
#define EBADRPC                        0x40000048	/* RPC struct is bad */
#define ERPCMISMATCH                   0x40000049	/* RPC version wrong */
#define EPROGUNAVAIL                   0x4000004a	/* RPC program not available */
#define EPROGMISMATCH                  0x4000004b	/* RPC program version wrong */
#define EPROCUNAVAIL                   0x4000004c	/* RPC bad procedure for program */
#define ENOLCK                         0x4000004d	/* No locks available */
#define EFTYPE                         0x4000004f	/* Inappropriate file type or format */
#define EAUTH                          0x40000050	/* Authentication error */
#define ENEEDAUTH                      0x40000051	/* Need authenticator */
#define ENOSYS                         0x4000004e	/* Function not implemented */
#define ENOTSUP                        0x40000076	/* Not supported */
#define EILSEQ                         0x4000006a	/* Invalid or incomplete multibyte or wide character */
#define EBACKGROUND                    0x40000064	/* Inappropriate operation for background process */
#define EDIED                          0x40000065	/* Translator died */
#define ED                             0x40000066	/* ? */
#define EGREGIOUS                      0x40000067	/* You really blew it this time */
#define EIEIO                          0x40000068	/* Computer bought the farm */
#define EGRATUITOUS                    0x40000069	/* Gratuitous error */
#define EBADMSG                        0x4000006b	/* Bad message */
#define EIDRM                          0x4000006c	/* Identifier removed */
#define EMULTIHOP                      0x4000006d	/* Multihop attempted */
#define ENODATA                        0x4000006e	/* No data available */
#define ENOLINK                        0x4000006f	/* Link has been severed */
#define ENOMSG                         0x40000070	/* No message of desired type */
#define ENOSR                          0x40000071	/* Out of streams resources */
#define ENOSTR                         0x40000072	/* Device not a stream */
#define EOVERFLOW                      0x40000073	/* Value too large for defined data type */
#define EPROTO                         0x40000074	/* Protocol error */
#define ETIME                          0x40000075	/* Timer expired */
#define ECANCELED                      0x40000077	/* Operation canceled */

/* Errors from <mach/message.h>.  */
#define EMACH_SEND_IN_PROGRESS         0x10000001
#define EMACH_SEND_INVALID_DATA        0x10000002
#define EMACH_SEND_INVALID_DEST        0x10000003
#define EMACH_SEND_TIMED_OUT           0x10000004
#define EMACH_SEND_WILL_NOTIFY         0x10000005
#define EMACH_SEND_NOTIFY_IN_PROGRESS  0x10000006
#define EMACH_SEND_INTERRUPTED         0x10000007
#define EMACH_SEND_MSG_TOO_SMALL       0x10000008
#define EMACH_SEND_INVALID_REPLY       0x10000009
#define EMACH_SEND_INVALID_RIGHT       0x1000000a
#define EMACH_SEND_INVALID_NOTIFY      0x1000000b
#define EMACH_SEND_INVALID_MEMORY      0x1000000c
#define EMACH_SEND_NO_BUFFER           0x1000000d
#define EMACH_SEND_NO_NOTIFY           0x1000000e
#define EMACH_SEND_INVALID_TYPE        0x1000000f
#define EMACH_SEND_INVALID_HEADER      0x10000010
#define EMACH_RCV_IN_PROGRESS          0x10004001
#define EMACH_RCV_INVALID_NAME         0x10004002
#define EMACH_RCV_TIMED_OUT            0x10004003
#define EMACH_RCV_TOO_LARGE            0x10004004
#define EMACH_RCV_INTERRUPTED          0x10004005
#define EMACH_RCV_PORT_CHANGED         0x10004006
#define EMACH_RCV_INVALID_NOTIFY       0x10004007
#define EMACH_RCV_INVALID_DATA         0x10004008
#define EMACH_RCV_PORT_DIED            0x10004009
#define EMACH_RCV_IN_SET               0x1000400a
#define EMACH_RCV_HEADER_ERROR         0x1000400b
#define EMACH_RCV_BODY_ERROR           0x1000400c

/* Errors from <mach/kern_return.h>.  */
#define EKERN_INVALID_ADDRESS          1
#define EKERN_PROTECTION_FAILURE       2
#define EKERN_NO_SPACE                 3
#define EKERN_INVALID_ARGUMENT         4
#define EKERN_FAILURE                  5
#define EKERN_RESOURCE_SHORTAGE        6
#define EKERN_NOT_RECEIVER             7
#define EKERN_NO_ACCESS                8
#define EKERN_MEMORY_FAILURE           9
#define EKERN_MEMORY_ERROR             10
#define EKERN_NOT_IN_SET               12
#define EKERN_NAME_EXISTS              13
#define EKERN_ABORTED                  14
#define EKERN_INVALID_NAME             15
#define EKERN_INVALID_TASK             16
#define EKERN_INVALID_RIGHT            17
#define EKERN_INVALID_VALUE            18
#define EKERN_UREFS_OVERFLOW           19
#define EKERN_INVALID_CAPABILITY       20
#define EKERN_RIGHT_EXISTS             21
#define EKERN_INVALID_HOST             22
#define EKERN_MEMORY_PRESENT           23
#define EKERN_WRITE_PROTECTION_FAILURE 24
#define EKERN_TERMINATED               26
#define EKERN_TIMEDOUT                 27
#define EKERN_INTERRUPTED              28

/* Errors from <mach/mig_errors.h>.  */
#define EMIG_TYPE_ERROR                -300	/* client type check failure */
#define EMIG_REPLY_MISMATCH            -301	/* wrong reply message ID */
#define EMIG_REMOTE_ERROR              -302	/* server detected error */
#define EMIG_BAD_ID                    -303	/* bad request message ID */
#define EMIG_BAD_ARGUMENTS             -304	/* server type check failure */
#define EMIG_NO_REPLY                  -305	/* no reply should be sent */
#define EMIG_EXCEPTION                 -306	/* server raised exception */
#define EMIG_ARRAY_TOO_LARGE           -307	/* array not large enough */
#define EMIG_SERVER_DIED               -308	/* server died */
#define EMIG_DESTROY_REQUEST           -309	/* destroy request with no reply */

/* Errors from <device/device_types.h>.  */
#define ED_IO_ERROR                    2500	/* hardware IO error */
#define ED_WOULD_BLOCK                 2501	/* would block, but D_NOWAIT set */
#define ED_NO_SUCH_DEVICE              2502	/* no such device */
#define ED_ALREADY_OPEN                2503	/* exclusive-use device already open */
#define ED_DEVICE_DOWN                 2504	/* device has been shut down */
#define ED_INVALID_OPERATION           2505	/* bad operation for device */
#define ED_INVALID_RECNUM              2506	/* invalid record (block) number */
#define ED_INVALID_SIZE                2507	/* invalid IO size */
#define ED_NO_MEMORY                   2508	/* memory allocation failure */
#define ED_READ_ONLY                   2509	/* device cannot be written to */

#define _HURD_ERRNOS 120

#endif /* bits/errno.h.  */
