ifeq ($(subdir),string)
sysdep_routines += \
  strlen-aligned \
  strlen-lsx \
  strlen-lasx \
  strnlen-aligned \
  strnlen-lsx \
  strnlen-lasx \
  strchr-aligned \
  strchr-lsx \
  strchr-lasx \
  strchrnul-aligned \
  strchrnul-lsx \
  strchrnul-lasx \
  strcmp-aligned \
  strcmp-lsx \
  strncmp-aligned \
  strncmp-lsx \
  memcpy-aligned \
  memcpy-unaligned \
  memmove-unaligned \
  memmove-lsx \
  memmove-lasx \
# sysdep_routines
endif
