ifeq ($(subdir),string)
sysdep_routines += \
  strlen-aligned \
  strlen-lsx \
  strlen-lasx \
  strchr-aligned \
  strchr-lsx \
  strchr-lasx \
  strchrnul-aligned \
  strchrnul-lsx \
  strchrnul-lasx \
# sysdep_routines
endif
