#! /bin/sh

# This test-case is the tzfile for America/Asuncion
# generated by tzlib-2021e as follows, using the tzlib-2021e
# zic: "zic -d DEST -r @1546300800 -L /dev/null -b slim
# SOURCE/southamerica".  Note that in its type 2 header, it
# has two entries in its "time-types" array (types), but
# only one entry in its "transition types" array
# (type_idxs).

printf \
'TZif2\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0'\
'\0\0\0\0\0\0\0\1\0\0\0\1\0\0\0\0\0\0\0TZif2\0\0\0\0\0\0\0\0'\
'\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\1\0\0\0\2\0\0\0\b\0'\
'\0\0\0\*\255\200\1\0\0\0\0\0\0\377\377\325\320\1\4-00\0-03\0\n'\
'<-04>4<-03>,M10.1.0/0,M3.4.0/0\n'
