ifeq ($(subdir),string)
sysdep_routines += \
  memchr_generic \
  memchr_nosimd \
  memcpy_a64fx \
  memcpy_generic \
  memcpy_mops \
  memcpy_oryon1 \
  memcpy_sve \
  memmove_mops \
  memset_a64fx \
  memset_emag \
  memset_generic \
  memset_kunpeng \
  memset_mops \
  memset_oryon1 \
  memset_sve_zva64 \
  memset_zva64 \
  strlen_asimd \
  strlen_generic \
# sysdep_routines
endif
