ifeq ($(subdir),string)
sysdep_routines += \
  memchr_generic \
  memchr_nosimd \
  memcpy_a64fx \
  memcpy_falkor \
  memcpy_generic \
  memcpy_mops \
  memcpy_sve \
  memcpy_thunderx \
  memcpy_thunderx2 \
  memmove_mops \
  memset_a64fx \
  memset_emag \
  memset_falkor \
  memset_generic \
  memset_kunpeng \
  memset_mops \
  strlen_asimd \
  strlen_mte \
# sysdep_routines
endif
