#if __GNUC_PREREQ (13, 0)
# define USE_LOGB_BUILTIN 1
# define USE_LOGBF_BUILTIN 1
#else
# define USE_LOGB_BUILTIN 0
# define USE_LOGBF_BUILTIN 0
#endif

#define USE_LOGBL_BUILTIN 0
#define USE_LOGBF128_BUILTIN 0
